### ISSUE TITLE
Poller should resume after condition is met again

### ISSUE THREAD

**Issue by okonet** [uzikilon/backbone-poller#21]
Right now it stops the poller completely, but I think it would be more convenient to continue to validate the condition on timer and resume polling if the condition became true again.

**Comment by Addvilz** [comment]
I have a exact same problem to solve which could be abstracted away if condition would be validated on timer, not just once and then stop poller. 

I think this is a quite popular case. Another point being, poller does directly invoke fetch on the model/collection, so unless we want to extend all of our models, we have to either introduce a global state (bad) or hack (bad enough).

**Comment by uzikilon** [comment]
Conceptually, the way I see it, a poller is a very simple helper utility that you can tell - hey, go fetch this things repeatedly until a condition is met.

I am trying to avoid multiple running timers that can heart performance.

Can you share a little more about your specific use case so I can better understand what problem are we not solving and how can we better approach it?

**Comment by Addvilz** [comment]
Hi. Thanks for your consideration! My specific case was that poller in our mvc architecture is defined N layers above views, where we catch event that something is being edited and poller should stop updating. Therefore to stop poller we must emit a global event or do something hackish. 

This could probably be solved by continuously evaluating the condition method, on each tick, and if the condition is false, continue to next tick.

**Comment by uzikilon** [comment]
So I was looking into this, and it looks like the current implementation of the poller is not designed to keep a timer running, when its off, because the current timer is a timeout that depends on an ajax call. It will actually start counting from the time the request is done. Unfortunately I don't have the time right now for a major refactor. If anybody else is willing to help, I'll be happy to accept any pull request.

**Comment by uzikilon** [comment]
Closing this ticket for now. Will reopen if this becomes relevant again.
