### ISSUE TITLE
Not compatible with lodash

### ISSUE THREAD

**Issue by scott-w** [uzikilon/backbone-poller#45]
Hi @uzikilon, thanks for making this project!

I've been building a project using lodash instead of underscore and I think I've found an issue where `_.each` is called in `set` (https://github.com/uzikilon/backbone-poller/blob/master/backbone.poller.js#L98) using `this` - which doesn't seem to be supported by lodash.

This means whenever `Poller.get(model)` is called, an error is raised.

**Comment by uzikilon** [comment]
If you can submit a PR replacing `_.each` with native `[].forEach` i'll be happy to accept it
